### ISSUE TITLE
Panta step "-p add" fails: missing pangenome.fasta file

### ISSUE THREAD

**Issue by chatcrawler** [amromics/pasa#2]
Hello.

I have installed Pasa_panta via conda, according to your description:

```
conda create -y -c conda-forge -c defaults --name panta python=3.7 mamba

conda activate panta

mamba install -y -c conda-forge -c bioconda -c anaconda -c defaults  --file requirements.txt
```

To test the installation I have run the -p init in your example from within the cloned panta git:

```
conda activate panta
python panta.py -p init -g examples/test/init/*.gff.gz -o examples/test/output

```

This works fine, but no "reference_pangenome.fasta" is produced.

Hence, running the tool with -p add will produce an error:

```
(panta) usys-cx-dock-11-285:Pasa_Panta-main user$ python panta.py -p add -a examples/test/add/*.fna.gz -o examples/test/output
Traceback (most recent call last):
  File "panta.py", line 358, in <module>
    main()
  File "panta.py", line 355, in main
    add_function(args)
  File "panta.py", line 267, in add_function
    check_dir_exist(old_representative_fasta)
  File "/Users/user/Pasa_Panta-main/pan_genome/utils.py", line 21, in check_dir_exist
    raise Exception(f'{path} does not exist')
Exception: examples/test/output/reference_pangenome.fasta does not exist
```

I am not sure what can be done to produce the missing *fasta file in output.

Thanks for much your help.

Cheers.

Seb

**Comment by vanhoan310** [comment]
Thank you for your interest in running our software. I have put a backup version of Pasa-compatible Panta here:
https://github.com/vanhoan310/Pasa_Panta

Here is the instruction to run Pasa: https://github.com/amromics/pasa/blob/main/Reproducibility/runPasaPipeline.py

A sample reference data can be found here: https://drive.google.com/file/d/1KUc6PWOxQxiW0M3fnp6MoUcjuoLL49Hj/view?usp=sharing

Please let me know if you have any question.
